fix

diff --git a/.github/workflows/exp.yml b/.github/workflows/exp.yml
--- a/.github/workflows/exp.yml
+++ b/.github/workflows/exp.yml
@@ -37,14 +37,18 @@ jobs:
             VERSION=${BRANCH#release/}
             if [ "$VERSION" != "$BRANCH" ]; then
                 echo "Triggered by commit in version $VERSION release branch $BRANCH"
-                git fetch origin refs/tags/v$VERSION:refs/tags/v$VERSION
+                #git fetch origin refs/tags/v$VERSION:refs/tags/v$VERSION
+                #if [ $? -ne 0 ]; then
+                #    echo "Tag v$VERSION does not exist"
+                #else
+                    #TAGSHA=$(git rev-parse v$VERSION)
+                TAGSHA=$(git rev-parse ref/tags/v$VERSION)
                 if [ $? -ne 0 ]; then
                     echo "Tag v$VERSION does not exist"
                 else
-                    TAGSHA=$(git rev-parse v$VERSION)
                     echo "FOUND TAG $TAGSHA"
                     if [ "$TAGSHA" != "${{ github.sha }}" ]; then
-                        echo "TAG v$VERSION exists on another commit : error"
+                        echo "TAG v$VERSION exists on another commit (${{ github.sha }}) : error"
                         exit 1
                     else
                         echo "Tag v$VERSION exists on this commit: nothing to do here"
